export const europeanCountries = [{code: 0, short: "", name: "Select Destination Country"},
    { code: 61, short: "AUD", symbol: "$", name: "Australia" },
    { code: 43, short: "EUR", symbol: "€", name: "Austria" },
    { code: 32, short: "EUR", symbol: "€", name: "Belgium" },
    { code: 359, short: "BGN", symbol: "лв", name: "Bulgaria" },
    { code: 1, short: "CAD", symbol: "$", name: "Canada" },
    { code: 385, short: "HRK", symbol: "kn", name: "Croatia" },
    { code: 357, short: "CYP", symbol: "£", name: "Cyprus" },
    { code: 420, short: "CZK", symbol: "Kč", name: "Czech Republic" },
    { code: 45, short: "DKK", symbol: "kr.", name: "Denmark" },
    { code: 358, short: "EUR", symbol: "€", name: "Finland" },
    { code: 33, short: "EUR", symbol: "€", name: "France" },
    { code: 49, short: "EUR", symbol: "€", name: "Germany" },
    { code: 30, short: "EUR", symbol: "€", name: "Greece" },
    { code: 36, short: "HUF", symbol: "Ft", name: "Hungary" },
    { code: 353, short: "EUR", symbol: "€", name: "Ireland" },
    { code: 39, short: "EUR", symbol: "€", name: "Italy" },
    { code: 371, short: "LVL", symbol: "Ls", name: "Latvia" },
    { code: 370, short: "LTL", symbol: "Lt", name: "Lithuania" },
    { code: 352, short: "EUR", symbol: "€", name: "Luxembourg" },
    { code: 356, short: "MTL", symbol: "₤", name: "Malta" },
    { code: 31, short: "EUR", symbol: "€", name: "Netherlands" },
    { code: 48, short: "PLN", symbol: "zl", name: "Poland" },
    { code: 351, short: "EUR", symbol: "€", name: "Portugal" },
    { code: 40, short: "RON", symbol: "lei", name: "Romania" },
    { code: 421, short: "SKK", symbol: "Sk", name: "Slovakia" },
    { code: 386, short: "EUR", symbol: "€", name: "Slovania" },
    { code: 34, short: "EUR", symbol: "€", name: "Spain" },
    { code: 46, short: "SEK", symbol: "kr", name: "Sweden" },
    { code: 44, short: "GBP", symbol: "£", name: "United Kingdom" },
    { code: 1, short: "USD", symbol: "$", name: "United States" }
];
export const mixedCountries = [{code: 0, short: "", name: "Select Destination Country"},
    { code: 61, short: "AUD", symbol: "$", name: "Australia", type: "w" },
    { code: 43, short: "EUR", symbol: "€", name: "Austria", type: "w" },
    { code: 32, short: "EUR", symbol: "€", name: "Belgium", type: "w" },
    { code: 359, short: "BGN", symbol: "лв", name: "Bulgaria", type: "w"  },
    { code: 237, short: "XAF", symbol: "FCFA", name: "Cameroun", type: "a"  },
    { code: 1, short: "CAD", symbol: "$", name: "Canada", type: "w"  },
    { code: 385, short: "HRK", symbol: "kn", name: "Croatia", type: "w"  },
    { code: 357, short: "CYP", symbol: "£", name: "Cyprus", type: "w"  },
    { code: 420, short: "CZK", symbol: "Kč", name: "Czech Republic", type: "w"  },
    { code: 45, short: "DKK", symbol: "kr.", name: "Denmark", type: "w"  },
    { code: 268, short: "SZL", symbol: "E", name: "Eswatini", type: "a"  },
    { code: 358, short: "EUR", symbol: "€", name: "Finland", type: "w"  },
    { code: 33, short: "EUR", symbol: "€", name: "France", type: "w"  },
    { code: 49, short: "EUR", symbol: "€", name: "Germany", type: "w"  },
    { code: 233, short: "GHC", symbol: "GH₵", name: "Ghana", type: "a"  },
    { code: 30, short: "EUR", symbol: "€", name: "Greece", type: "w"  },
    { code: 36, short: "HUF", symbol: "Ft", name: "Hungary", type: "w"  },
    { code: 353, short: "EUR", symbol: "€", name: "Ireland", type: "w"  },
    { code: 39, short: "EUR", symbol: "€", name: "Italy", type: "w"  },
    { code: 254, short: "KES", symbol: "KSh", name: "Kenya", type: "a"  },
    { code: 266, short: "LSL", symbol: "L", name: "Lesotho", type: "a"  },
    { code: 371, short: "LVL", symbol: "Ls", name: "Latvia", type: "w"  },
    { code: 370, short: "LTL", symbol: "Lt", name: "Lithuania", type: "w"  },
    { code: 352, short: "EUR", symbol: "€", name: "Luxembourg", type: "w"  },
    { code: 223, short: "XOF", symbol: "CFA", name: "Mali", type: "a"  },
    { code: 356, short: "MTL", symbol: "₤", name: "Malta", type: "a"  },
    { code: 264, short: "NAD", symbol: "$", name: "Namibia", type: "a"  },
    { code: 31, short: "EUR", symbol: "€", name: "Netherlands", type: "w"  },
    { code: 234, short: "NGN", symbol: "₦", name: "Nigeria", type: "a"  },
    { code: 48, short: "PLN", symbol: "zl", name: "Poland", type: "w"  },
    { code: 351, short: "EUR", symbol: "€", name: "Portugal", type: "w"  },
    { code: 40, short: "RON", symbol: "lei", name: "Romania", type: "w"  },
    { code: 250, short: "RWF", symbol: "FRw", name: "Rwanda", type: "a"  },
    { code: 221, short: "XOF", symbol: "CFA", name: "Senegal", type: "a"  },
    { code: 232, short: "SLL", symbol: "Le", name: "Sierra Leone", type: "a"  },
    { code: 421, short: "SKK", symbol: "Sk", name: "Slovakia", type: "w"  },
    { code: 386, short: "EUR", symbol: "€", name: "Slovania", type: "w"  },
    { code: 27, short: "ZAR", symbol: "R", name: "South Africa", type: "a"  },
    { code: 34, short: "EUR", symbol: "€", name: "Spain", type: "w"  },
    { code: 46, short: "SEK", symbol: "kr", name: "Sweden", type: "w"  },
    { code: 256, short: "UGX", symbol: "USh", name: "Uganda", type: "a"  },
    { code: 44, short: "GBP", symbol: "£", name: "United Kingdom", type: "w"  },
    { code: 1, short: "USD", symbol: "$", name: "United States", type: "w"  },
    { code: 260, short: "ZMK", symbol: "ZK", name: "Zambia", type: "a"  }

];
export const africanCountries = [{code: 0, short: "", name: "Select Destination Country"},
    { code: 237, short: "XAF", symbol: "FCFA", name: "Cameroun" },
    { code: 268, short: "SZL", symbol: "E", name: "Eswatini" },
    { code: 233, short: "GHC", symbol: "GH₵", name: "Ghana" },
    { code: 225, short: "XOF", symbol: "CFA", name: "Ivory Coast" },
    { code: 254, short: "KES", symbol: "KSh", name: "Kenya" },
    { code: 266, short: "LSL", symbol: "L", name: "Lesotho" },
    { code: 223, short: "XOF", symbol: "CFA", name: "Mali" },
    { code: 264, short: "NAD", symbol: "$", name: "Namibia" },
    { code: 234, short: "NGN", symbol: "₦", name: "Nigeria" },
    { code: 250, short: "RWF", symbol: "FRw", name: "Rwanda" },
    { code: 221, short: "XOF", symbol: "CFA", name: "Senegal" },
    { code: 232, short: "SLL", symbol: "Le", name: "Sierra Leone" },
    { code: 27, short: "ZAR", symbol: "R", name: "South Africa" },
    { code: 256, short: "UGX", symbol: "USh", name: "Uganda" },
    { code: 260, short: "ZMK", symbol: "ZK", name: "Zambia" }
];
export const africanCountriesForReceive = [{code: 0, short: "", name: "Select Origin Country"},
    { code: 237, short: "XAF", symbol: "FCFA", name: "Cameroun" },
    { code: 268, short: "SZL", symbol: "E", name: "Eswatini" },
    { code: 233, short: "GHC", symbol: "GH₵", name: "Ghana" },
    { code: 225, short: "XOF", symbol: "CFA", name: "Ivory Coast" },
    { code: 254, short: "KES", symbol: "KSh", name: "Kenya" },
    { code: 266, short: "LSL", symbol: "L", name: "Lesotho" },
    { code: 223, short: "XOF", symbol: "CFA", name: "Mali" },
    { code: 264, short: "NAD", symbol: "$", name: "Namibia" },
    { code: 234, short: "NGN", symbol: "₦", name: "Nigeria" },
    { code: 250, short: "RWF", symbol: "FRw", name: "Rwanda" },
    { code: 221, short: "XOF", symbol: "CFA", name: "Senegal" },
    { code: 232, short: "SLL", symbol: "Le", name: "Sierra Leone" },
    { code: 27, short: "ZAR", symbol: "R", name: "South Africa" },
    { code: 256, short: "UGX", symbol: "USh", name: "Uganda" },
    { code: 260, short: "ZMK", symbol: "ZK", name: "Zambia" }
];